# Generated by Django 4.2.3 on 2024-06-28 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="related_users",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
